### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Hygieux** [arthurb123/ERregulator#3] opened 2024-07-28 15:23 UTC
Okay it says its randomized, but its not so maybe its something I did, I am not sure.

**Comment by Kaciej12** [comment] 2024-08-29 07:56
It doesn't work for me. I've tried both the regulation file of item and enemy randomizer as well as vanilla regulation file without any other mods. Got following errors as in atached images.
![randomizer](https://github.com/user-attachments/assets/d9ceca6f-b7d7-46b0-9c5d-7059be59d394)
![norandomizer](https://github.com/user-attachments/assets/daf02af8-604c-4a19-8bf2-01cdc9416fd7)

**Comment by arthurb123** [comment] 2024-08-29 10:07
Hello. The randomizer currently only supports Elden Ring _pre-DLC_. The DLC adds all kinds of new items, equipment, etc; Which changes the initially supported regulation structure of the game. In the near future I do plan on updating the randomizer when I have the time. Or, if someone else sees this and would like to create a pull request, that would be greatly appreciated. 
Sorry for the caused inconvenience!

**Comment by arthurb123** [comment] 2024-09-14 19:02
Hello again. The randomizer has been updated to support the DLC. The new release can be found [on the releases page listed as version 2.0](https://github.com/arthurb123/ERregulator/releases/tag/v2.0). I will be closing this issue, if you have any other questions regarding the randomizer or the new release please create a new issue.

**Closed as completed by arthurb123** 2024-09-14 19:02 UTC
Labels: bug, help wanted
